### ISSUE TITLE
vim.o.timeoutlen 设置时间过短导致gd绑定无法触发

### ISSUE THREAD

**Issue by allenzt** [nshen/learn-neovim-lua#1]
感谢分享neovim lua配置！

我在使用过程中发现vim.o.timeoutlen=100， 导致gd(跳转到定义无法触发）， 设置这个值是有什么考虑吗？是否需要在文档中提示下？

**Comment by nshen** [comment]
HI，@allenzt 这个值应该是 vim 等待连击的时间100毫秒，理论上应该是按`g`后等待100毫秒内按`d`，就会触发。

我也是参考其他配置设置的，以为是越短越好，暂时还没遇到问题。

如果有问题取消掉这条也应该没什么问题吧，你设置了多少会恢复正常呢？ 我去文档里提示一下，非常感谢。

**Comment by allenzt** [comment]
@nshen 谢谢回复，我直接把这条命令注释掉了， 使用了默认的timeout参数
