### ISSUE TITLE
mac icon显示有问题

### ISSUE THREAD

**Issue by fengtianru117** [nshen/learn-neovim-lua#10]

**Comment by fengtianru117** [comment]
![image](https://user-images.githubusercontent.com/27802344/150089821-6da851a8-701c-4cf3-908a-7aebb16c2a31.png)
![image](https://user-images.githubusercontent.com/27802344/150089867-63a562f0-1725-48f8-a0fc-28c896c4e33b.png)
![image](https://user-images.githubusercontent.com/27802344/150089913-fbd648cc-6a35-4fea-808c-1657407a2063.png)
![image](https://user-images.githubusercontent.com/27802344/150089929-151f81bb-cdb4-43f3-9341-8d458a0a481f.png)
![image](https://user-images.githubusercontent.com/27802344/150089972-4c5aaf84-043c-48eb-b382-da754f4e141c.png)

已经安装了nerdicon了 还是不行

**Comment by nshen** [comment]
要在terminal里选安装的nerdfont字体，你的第一张图选的字体是不是不对，名字一般是是xxx NF吧

**Comment by fengtianru117** [comment]
谢谢 已经解决了
