### ISSUE TITLE
设置快捷键报错

### ISSUE THREAD

**Issue by fengtianru117** [nshen/learn-neovim-lua#11]
这是报错
![image](https://user-images.githubusercontent.com/27802344/150915746-3068d6e6-70c1-43e4-9302-56b91fbd6660.png)
这是我的init.vim文件
![image](https://user-images.githubusercontent.com/27802344/150915792-5c63b4ad-85c5-4524-a775-04b2fc073fbf.png)
这是我的目录结构
![image](https://user-images.githubusercontent.com/27802344/150915839-4548a2c6-2803-4453-bbd7-046ebe722593.png)
这是我的keybindings文件内容，说map是nil
![image](https://user-images.githubusercontent.com/27802344/150915874-66bd94e5-d487-457c-9470-8a1ae1ab8e1e.png)
请问如何解决呢，卡了我挺久的

**Comment by nshen** [comment]
![image](https://user-images.githubusercontent.com/181506/150920156-125fa9e8-eba0-4376-99ad-457dbc3e83a5.png)

为什么会有个k  🤣

**Comment by fengtianru117** [comment]
感谢大佬 另外我想问下 为什么我的全局变量vim不被lsp识别 会提示我undefine global vim 强迫症很难接受，这个困扰我挺久的了> ![image](https://user-images.githubusercontent.com/181506/150920156-125fa9e8-eba0-4376-99ad-457dbc3e83a5.png)
> 
> 
> 
> 为什么会有个k  🤣

**Comment by nshen** [comment]
lua.lua 文件是用的这个吗？ 还是直接返回 {} 了？
https://github.com/nshen/learn-neovim-lua/blob/main/lua/lsp/lua.lua
