### ISSUE TITLE
文档描述有笔误

### ISSUE THREAD

**Issue by xiaolitongxue666** [nshen/learn-neovim-lua#12]
![image](https://user-images.githubusercontent.com/35646108/151587684-5da33289-604d-4491-b70d-c0d6c1f1bedf.png)

应该是 nvim-treesitter.lua

**Comment by nshen** [comment]
> ![image](https://user-images.githubusercontent.com/35646108/151587684-5da33289-604d-4491-b70d-c0d6c1f1bedf.png)
> 
> 应该是 nvim-treesitter.lua

谢谢大佬

**Comment by xiaolitongxue666** [comment]
> > ![image](https://user-images.githubusercontent.com/35646108/151587684-5da33289-604d-4491-b70d-c0d6c1f1bedf.png)
> > 应该是 nvim-treesitter.lua
> 
> 谢谢大佬

哈哈 你才大佬好吧 之前在twitter和你聊过 我这里配置也是才转到lua，还有一些问题会向您请教的
