### ISSUE TITLE
请问有没有解决bufferline和nvim tree 会关闭所有buffer得问题

### ISSUE THREAD

**Issue by mikaizhu** [nshen/learn-neovim-lua#14]
我下载bufferline后，使用bdelete会关闭当前buffer，但我下载nvim tree后，使用同一命令，却会退出整个nvim

**Comment by nshen** [comment]
hi @mikaizhu 我现在是这样，安装时依赖这个 [moll/vim-bbye](https://github.com/moll/vim-bbye)

```lua
 -- bufferline
    use({"akinsho/bufferline.nvim", requires = { "kyazdani42/nvim-web-devicons", "moll/vim-bbye" }})
```
然后配置时用 Bdelete 代替 bdelete

```lua
bufferline.setup({
  options = {
    -- 关闭 Tab 的命令
    close_command = "Bdelete! %d",
    right_mouse_command = "Bdelete! %d",
........................
```

你试试行不行

**Comment by mikaizhu** [comment]
> hi @mikaizhu 我现在是这样，安装时依赖这个 [moll/vim-bbye](https://github.com/moll/vim-bbye)
> 
> ```lua
>  -- bufferline
>     use({"akinsho/bufferline.nvim", requires = { "kyazdani42/nvim-web-devicons", "moll/vim-bbye" }})
> ```
> 
> 然后配置时用 Bdelete 代替 bdelete
> 
> ```lua
> bufferline.setup({
>   options = {
>     -- 关闭 Tab 的命令
>     close_command = "Bdelete! %d",
>     right_mouse_command = "Bdelete! %d",
> ........................
> ```
> 
> 你试试行不行

我使用这个解决了问题，感谢

**Comment by mikaizhu** [comment]
我刚才试了一下，如果我使用`:wq`来关闭buffer的话，会使得整个nvim-tree占领当前buffer，并且当前的buffer并没有关闭

**Comment by nshen** [comment]
> 我刚才试了一下，如果我使用`:wq`来关闭buffer的话，会使得整个nvim-tree占领当前buffer，并且当前的buffer并没有关闭

好像要把nvim-tree的 auto close 设置成 true 才行吧。

**Comment by mikaizhu** [comment]
嗯嗯，谢谢

**Comment by lzw-723** [comment]
我个人总结一下

nvim-tree开启AutoClose

[Auto Close](https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close#eliasa5)
 
用bufdelete.nvim（tips：引入后不用setup就能用）

[famiu/bufdelete.nvim](https://github.com/famiu/bufdelete.nvim)

配置bufferline的关闭命令

```lua
bufferline.setup({
  options = {
    -- 关闭 Tab 的命令
    close_command = "Bdelete! %d",
    ...
   }
})
```

效果

![nvim-test](https://picst.sunbangyan.cn/2023/08/18/uion08.gif)
