### ISSUE TITLE
Auto command does not enable automatic plugin update when `plugins.lua` is saved

### ISSUE THREAD

**Issue by uxfion** [nshen/learn-neovim-lua#147]
# 自动命令无法实现当`plugins.lua`保存后自动更新插件

## 版本

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@43b3775c8372

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```
## 背景

将原本`plugins.lua`中的自动安装移除

```lua
-- 每次保存 plugins.lua 自动安装插件
pcall(
    vim.cmd,
    [[
        augroup packer_user_config
        autocmd!
        autocmd BufWritePost plugins.lua source <afile> | PackerSync
        augroup end
    ]]
)
```

新增`autocmds.lua`

```
-- 修改lua/plugins.lua 自动更新插件
autocmd("BufWritePost", {
    group = myAutoGroup,
    -- autocmd BufWritePost plugins.lua source <afile> | PackerSync
    callback = function()
        if vim.fn.expand("<afile>") == "lua/plugins.lua" then
            vim.api.nvim_command("source lua/plugins.lua")
            vim.api.nvim_command("PackerSync")
        end
    end,
})
```

同时在`init.lua`中新增

```
require("autocmds")
```

## 问题

自动命令无法实现当`plugins.lua`保存后自动更新插件

`autocmds.lua`中

1. 进入Terminal 自动进入插入模式
2. 保存时自动格式化
3. Highlight on yank
4. 用o换行不要延续注释

均可以使用，**唯独自动更新插件无法使用**

## 问题配置

个人配置文件如下
https://github.com/uxfion/dotfiles

## 初步测试

将自动命令单独拎出来

```lua
local myAutoGroup = vim.api.nvim_create_augroup("myAutoGroup", {
    clear = true,
})

local autocmd = vim.api.nvim_create_autocmd
vim.notify("aaaaaaaaaaaaaaaaaaaaaaaaaa")

-- 修改lua/plugins.lua 自动更新插件
autocmd("BufWritePost", {
    group = myAutoGroup,
    -- autocmd BufWritePost plugins.lua source <afile> | PackerSync
    callback = function()
        print("bbbbbbbbbbbbbbbbbbbbbb")
        if vim.fn.expand("<afile>") == "lua/plugins.lua" then
            print("cccccccccccccccccccccc")
--            vim.api.nvim_command("source lua/plugins.lua")
            vim.api.nvim_command("PackerSync")
        end
        print("dddddddddddddddddddddd")
    end,
})
```
aaaaaaaaaaaaaaaaaaaaaaaaaa 正常输出
bbbbbbbbbbbbbbbbbbbbbb 正常输出
dddddddddddddddddddddd 正常输出

<img width="367" alt="image" src="https://user-images.githubusercontent.com/44778029/204144832-8a642375-3bfd-439b-9ab0-ba8c5545ad77.png">

没有cccccccccccccccccccccc

`if vim.fn.expand("<afile>") == "lua/plugins.lua" then`判断出问题了？

**Comment by nshen** [comment]
在 bbbb 那里 log 一下，然后看看 plugins.lua 保存的时候输出什么值

print(vim.inspect(vim.fn.expand("<afile>")))

**Comment by uxfion** [comment]
是空""

<img width="388" alt="image" src="https://user-images.githubusercontent.com/44778029/204152421-c9f1544e-2069-4bc3-b393-1570bc27be78.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/44778029/204152450-fd8a5f9b-3057-460c-9c56-8d6c7fa1dc4f.png">

**Comment by uxfion** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44778029/204152559-95e6e0ef-1c9a-41f8-887c-1ebfd44aba55.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/44778029/204152570-c7ea1479-3bdd-4535-a213-ed30ded44393.png">

**Comment by uxfion** [comment]
## 解决方案

```
-- 修改lua/plugins.lua 自动更新插件
autocmd("BufWritePost", {
    group = myAutoGroup,
    -- autocmd BufWritePost plugins.lua source <afile> | PackerSync
    callback = function()
        if vim.fn.expand("<afile>") == ".config/nvim/lua/plugins.lua" then
            vim.api.nvim_command("source .config/nvim/lua/plugins.lua")
            vim.api.nvim_command("PackerSync")
        end
    end,
})
```
将`if vim.fn.expand("<afile>") == "lua/plugins.lua" then`修改为`if vim.fn.expand("<afile>") == ".config/nvim/lua/plugins.lua" then`，就正常了

## 疑问

为什么大家的都能匹配到`"lua/plugins.lua"`，而我的却是`".config/nvim/lua/plugins.lua"`？

是neovim版本问题造成的吗？
