### ISSUE TITLE
自动补全bug

### ISSUE THREAD

**Issue by ZinkWu** [nshen/learn-neovim-lua#16]
OS: Win11
SHELL: zsh
NVIM: v0.6.1

**bug描述**
输入: `:r !`
在`!`会很卡，经过大概 20 秒左右后会显示补全内容，但 UI 效果依旧很卡

**Comment by nshen** [comment]
hi 我不知道 `:r !`  命令是干什么的，但我也遇到过好几次某命令会卡住好几秒的事情，具体什么命令忘记了，甚至 nvim-tree 里某个快捷键都卡住，也忘了是哪个快捷键了，还好还好都不是常用的。
好像是都跟读系统路径有关，应该是wsl之类的问题，我觉得是无解。

**Comment by ZinkWu** [comment]
我将自动补全配置文件`nvim-cmp.lua`中`cmp.setup.cmdline`相关代码注释掉了，取消了命令行补全，就没有遇到这个问题了。
猜测是补全命令行是搜索量过大？

`:r !command` 可以直接将命令执行结果读取到当前 buffer 中

**Comment by nshen** [comment]
我也觉得好像是搜索量过大吧
