### ISSUE TITLE
插件安装失败有什么好办法

### ISSUE THREAD

**Issue by weizhenhuan** [nshen/learn-neovim-lua#18]
![image](https://user-images.githubusercontent.com/55399998/154812634-7dafe937-7699-46c9-bcbd-da191c0f9f24.png)
如题，插件安装一直提示失败

**Comment by nshen** [comment]
亲，试试这几个自定义源

```lua
packer.startup({
  function(use)
    -- Packer 可以升级自己
    use("wbthomason/packer.nvim")
    -------------------------- plugins --------------------------
.....
    -------------------------------------------------------
  end,

  config = {
    -- 最大并发数
    max_jobs = 16,
    -- 自定义源
    git = {
      -- default_url_format = "https://hub.fastgit.xyz/%s",
      --default_url_format = "https://mirror.ghproxy.com/https://github.com/%s",
      --default_url_format = "https://gitcode.net/mirrors/%s",
      -- default_url_format = "https://gitclone.com/github.com/%s",
    },
    -- display = {
    -- 使用浮动窗口显示
    --   open_fn = function()
    --     return require("packer.util").float({ border = "single" })
    --   end,
    -- },
  },
})

```

**Comment by fgqile** [comment]
我尝试了很多次的同步，目前打开neovim时，还会出现下面的报错，能帮忙看一下是什么意思嘛？
要怎么才能解决，多谢啦！
![image](https://user-images.githubusercontent.com/64899378/158345346-4c4f0907-eb2c-4fb3-ab1c-e4ddc6b1b161.png)

**Comment by fgqile** [comment]
进行nvim后。自动安装脚本执行后，如下如下的报错，

```
nvim-treesitter[javascript]: Error during tarball extraction.
gzip: stdin: unexpected end of file                                                                                              
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

![image](https://user-images.githubusercontent.com/64899378/158347671-dbbb973e-e455-4b9d-8cfc-bbc6df7a8667.png)

**Comment by nshen** [comment]
> 我尝试了很多次的同步，目前打开neovim时，还会出现下面的报错，能帮忙看一下是什么意思嘛？ 要怎么才能解决，多谢啦！ ![image](https://user-images.githubusercontent.com/64899378/158345346-4c4f0907-eb2c-4fb3-ab1c-e4ddc6b1b161.png)

找不到 onedark 配色，没装成功

**Comment by nshen** [comment]
> 进行nvim后。自动安装脚本执行后，如下如下的报错，
> 
> ```
> nvim-treesitter[javascript]: Error during tarball extraction.
> gzip: stdin: unexpected end of file                                                                                              
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> ```
> 
> ![image](https://user-images.githubusercontent.com/64899378/158347671-dbbb973e-e455-4b9d-8cfc-bbc6df7a8667.png)

这看上去还是网络问题，运行 `:TSUpdate` 重新下载语法文件

**Comment by fgqile** [comment]
> 这看上去还是网络问题，运行 `:TSUpdate` 重新下载语法文件


多谢啦，大佬忙里抽闲回答问题。感谢感谢。我再试试。以后会继续关注的
