### ISSUE TITLE
退出自动格式化文档怎么配置呢？

### ISSUE THREAD

**Issue by sober-wang** [nshen/learn-neovim-lua#29]
![image](https://user-images.githubusercontent.com/35804630/162206352-7ece447b-5a3b-4bc8-a64f-e43c7febb9dd.png)
我的这块配置一直没有生效过。

![image](https://user-images.githubusercontent.com/35804630/162206850-b7bbb3aa-37d4-48d0-ae19-0b8691c38eba.png)
绑定的按键也不生效。

**Comment by nshen** [comment]
自动命令我都改到 autocmds里了，你可以参考一下，需要 neovim 0.7

https://github.com/nshen/learn-neovim-lua/blob/main/lua/autocmds.lua

**Comment by sober-wang** [comment]
我发现最终的问题出现在 `vim.lsp.buf.formatting*()` 等方法必须要当前语言支持 format 才可以用。

我在你的项目中发现了 `mhartington/formatter.nvim` 插件，发现他可以尝试格式化一些语言，例如： lua ,python, golang 等

但是，我在格式化 *.go 文件的时候遇见了奇怪问题。

<img width="832" alt="image" src="https://user-images.githubusercontent.com/35804630/162742067-a310a9f0-b7d6-4db8-b3a6-23dc86ccfcea.png">


```lua
    go = {
      function()
        return {
          exe = "gofmt",
          --args = {
          --  "-w",
          --  vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)),
          --},
          stdin = true,
        }
      end,
    },
```

**Comment by sober-wang** [comment]
我解决了这个问题，golang `gofmt` `goimports` 格式化时使用制表符，制表符在 vim 显示为^I

**Comment by nshen** [comment]
hi，你是怎么解决的呢，我配置里设置了下边两行，还会显示制表符吗？

```
vim.o.list = true
vim.o.listchars = "space:·,tab:··"
```

**Comment by denstiny** [comment]
# 自动格式化
## packer 安装插件
```lua
    use { 'Chiel92/vim-autoformat' }

```
## 配置
```vim
"== 自动格式化
let g:formatdef_my_c = '"astyle --indent=spaces=2 -C -p -f -xg -xW -xe"'
let g:formatters_c = ['my_c']
let g:formatters_cpp= ['my_c']
let g:autoformat_verbosemode=1
au BufWrite *.c,*.cpp,*.java,*.h :Autoformat
```
