### ISSUE TITLE
trouble插件的配置解耦问题

### ISSUE THREAD

**Issue by Demon-Wang** [nshen/learn-neovim-lua#3]
我看plugins.lua和trouble本身的说明 都是说
在packer下直接设置config = .... 

这种情况下如何解耦到单独创建plugin-config目录下的单独配置文件呢。

不是很会lua和其他的内部原理。。 可能有点偏执，求指教。

期待更新！

**Comment by Demon-Wang** [comment]
我自己看了下 nvim-tree的readme 他也是config的写法  好像可以直接 另写lua 用setup载入config就行了

**Comment by nshen** [comment]
👍 放假没开机，才看到，两种方法应该是一样的。
