### ISSUE TITLE
引入autocmds.lua 报错

### ISSUE THREAD

**Issue by xiaojia21190** [nshen/learn-neovim-lua#30]
attempt to call field 'nvim_create_augroup' (a nil value)

**Comment by nshen** [comment]
nvim_create_augroup 是 neovim 0.7 的新 API，我尝试了一下，需要升级0.7 到prerelease，正式版应该也快出了

mac 可以直接 `brew install --HEAD neovim`

ubuntu 可以
```
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
```

**Comment by xiaojia21190** [comment]
> nvim_create_augroup 是 neovim 0.7 的新 API，我尝试了一下，需要升级0.7 到prerelease，正式版应该也快出了
> 
> mac 可以直接 `brew install --HEAD neovim`
> 
> ubuntu 可以
> ```
> sudo add-apt-repository ppa:neovim-ppa/unstable
> sudo apt-get update
> sudo apt-get install neovim
> ```

谢谢
