### ISSUE TITLE
打开neovim报错, bufferline.nvim安装失败

### ISSUE THREAD

**Issue by xxwang** [nshen/learn-neovim-lua#31]
环境:
mac-mini m1 系统终端zsh

问题1:
在挂代理的情况下运行:PackerSync的时候akinsho/bufferline.nvim始终更新失败

问题2:
在终端运行vim命令报错(直接用的作者的仓库文件)
Error detected while processing /Users/xxx/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/xxx/.config/nvim/lua/autocmds.lua:1: attempt to cal
l field 'nvim_create_augroup' (a nil value)
stack traceback:
        /Users/xxx/.config/nvim/lua/autocmds.lua:1: in main chunk
        [C]: in function 'require'
        /Users/xxx/.config/nvim/init.lua:10: in main chunk

**Comment by nshen** [comment]
1. 我觉得就是网络问题，多试几次，换个时间
2. 更新成今天刚发布的 neovim 0.7 正式版就好了
