### ISSUE TITLE
设置keybindings 不生效

### ISSUE THREAD

**Issue by wanxiankai** [nshen/learn-neovim-lua#32]
![image](https://user-images.githubusercontent.com/20761408/168823513-7fe28eab-dd50-49d2-b4f5-06ae8ff2d9e6.png)

.config/nvim/lua/keybindings.lua 中已经设置了对应的快捷键映射。

![image](https://user-images.githubusercontent.com/20761408/168823831-c177f21b-52d1-49eb-9e8b-e651e187c80a.png)
init.lua 中也已经require了

但是使用 `sc` 这类 `s` 开头的命令还是会删除当前字符并改为insert模式，其他的快捷键也都不生效，例如 leader + t 打开终端也不生效。

系统是wls2 ubuntu 22.04

**Comment by nshen** [comment]
既不报错也不生效还是挺奇怪的

1. 确定文件是否已经加载到了，`print(123)`，重启看看 `:messages`是否有123输出。
2. 然后看被映射的命令是否可用 `:vsp<CR>` 看看是否能分屏。
3. 最后看是不是快捷键被占用了，换成别的快捷键试试

**Comment by wanxiankai** [comment]
> 既不报错也不生效还是挺奇怪的
> 
> 1. 确定文件是否已经加载到了，`print(123)`，重启看看 `:messages`是否有123输出。
> 2. 然后看被映射的命令是否可用 `:vsp<CR>` 看看是否能分屏。
> 3. 最后看是不是快捷键被占用了，换成别的快捷键试试

**Comment by wanxiankai** [comment]
> 既不报错也不生效还是挺奇怪的
> 
> 1. 确定文件是否已经加载到了，`print(123)`，重启看看 `:messages`是否有123输出。
> 2. 然后看被映射的命令是否可用 `:vsp<CR>` 看看是否能分屏。
> 3. 最后看是不是快捷键被占用了，换成别的快捷键试试

1. 在keybindings 文件内新增了 `print(123)`, 重启之后使用 `:message` 没有123 输出，效果如下图：
![image](https://user-images.githubusercontent.com/20761408/168946896-ae4bb842-3ff5-45a5-b40a-daad48997ae8.png)

2. 被映射的命令可用：
![image](https://user-images.githubusercontent.com/20761408/168947031-5de9da4e-8ff8-42ba-9cf7-11937e05e3ff.png)

3. 这个我不清楚可以在哪里看到当前这个快捷键是否被占用，请问可以在哪里可以快速查看呢？

重复一下我的情况，我在设置了keybindings 这个文件，并且在init.lua 文件中导入了，但是这些快捷键都没有起效，目前看是所有的设置的快捷键都没效果，还不仅仅是某一个，所以我不清楚是哪里出了问题

**Comment by nshen** [comment]
你第一步就没有输出，说明 keybindings 就没有加载到，你可以在 init.lua 里print一下，重启后 `:messages`正常是这样的

<img width="328" alt="image" src="https://user-images.githubusercontent.com/181506/168955559-00c88cf7-b724-4fe6-84ab-33725d79420c.png">

看看你路径对不对吧

~/.config/nvim/init.lua

~/.config/nvim/lua/keybindings.lua

**Comment by wanxiankai** [comment]
> 你第一步就没有输出，说明 keybindings 就没有加载到，你可以在 init.lua 里print一下，重启后 `:messages`正常是这样的
> 
> <img alt="image" width="328" src="https://user-images.githubusercontent.com/181506/168955559-00c88cf7-b724-4fe6-84ab-33725d79420c.png">
> 
> 看看你路径对不对吧
> 
> ~/.config/nvim/init.lua
> 
> ~/.config/nvim/lua/keybindings.lua

----
![image](https://user-images.githubusercontent.com/20761408/168964105-438e966a-2158-4d43-a6f5-b021ecce05e1.png)
-我的路径如上图所示，应该是没啥问题的

![image](https://user-images.githubusercontent.com/20761408/168964304-930c4f15-f193-48bd-97dc-81770bf2e6b6.png)
![image](https://user-images.githubusercontent.com/20761408/168964331-b84ef773-c460-4671-825b-61683ea688b4.png)

在init.lua 里面加入了print语句，重启之后使用 `:messages` 之后还是之前那个提示，实在是不知道问题出在哪了

**Comment by nshen** [comment]
init.lua 都没有加载到，我搜了一下，你那句是其他插件报的， https://github.com/ycm-core/YouCompleteMe/issues/2748

你这个是vim还是nvim啊，是不是读了之前vim的配置

**Comment by wanxiankai** [comment]
> init.lua 都没有加载到，我搜了一下，你那句是其他插件报的， [ycm-core/YouCompleteMe#2748](https://github.com/ycm-core/YouCompleteMe/issues/2748)
> 
> 你这个是vim还是nvim啊，是不是读了之前vim的配置

确实是进了 vim 而不是 nvim， 使用 nvim 打开就没问题了，抱歉，我的错。

另外为什么使用 vim 这个命令，是因为之前按照课程所说的进行了 `vim` `vi` 和 `v`这几个键的映射，我在 ` .bashrc` 中设置之后 执行 `source ~/.bashrc` 终端卡在了下面的情况下：

![e12586d9193d3e3948e17f1adb28690](https://user-images.githubusercontent.com/20761408/169026491-0ce992ab-117f-4db9-97f9-8ced13b871c0.png)

根据群里其他人的提示，我将设置映射的语句填写到了 ~/.profile 文件中：
![image](https://user-images.githubusercontent.com/20761408/169026767-5d5ffc23-8e0b-4b6e-8acc-72bdd8ffb687.png)

然后 `source ~/.profile` 并没有报错，因此以为设置成功了，之后就一直使用vim进入了，这才导致了上面的问题

**Comment by nshen** [comment]
你那个bash有命令报错 shopt 找不到，所以没执行到设置别名呢。你先搜一下把那个报错解决就好了
