### ISSUE TITLE
attempt to call field "cmp_format" ( a nil value)

### ISSUE THREAD

**Issue by fgqile** [nshen/learn-neovim-lua#34]
When I want open the nvim, I get this error.
This computer is ubuntu 16.04

`
 Error detected while processing /home/auto/.config/nvim/init.lua:                                                                                                 E5113: Error while calling lua chunk: /home/auto/.config/nvim/lua/lsp/ui.lua:117: attempt to call field 'cmp_format' (a nil value)                                                    stack traceback:                                                                                                                                                                              /home/auto/.config/nvim/lua/lsp/ui.lua:117: in main chunk                                                                                                                     
        [C]: in function 'require'                                                                                                                                                    
        /home/auto/.config/nvim/lua/lsp/cmp.lua:43: in main chunk                                                                                                                     
        [C]: in function 'require'                                                                                                                                                    
        /home/auto/.config/nvim/init.lua:27: in main chunk                                                                                                                            
Press ENTER or type command to continue 
`

![image](https://user-images.githubusercontent.com/64899378/170963178-a532c63a-c633-4d41-b865-5b493cd7c56b.png)

![image](https://user-images.githubusercontent.com/64899378/170963249-455ee568-c75c-4f28-bf5f-2bcdd4d93cbe.png)

Can you give me some advise?

**Comment by nshen** [comment]
`attempt to call field 'cmp_format' (a nil value) `

cmp_format is a method of lspkind

you should try uninstall lspkind first, then reinstall it

`use("onsails/lspkind-nvim")`

**Comment by fgqile** [comment]
已经解决了，我清除了所有插件，然后重新安装，之后没有问题了。多谢帮忙。
