### ISSUE TITLE
/.config/nvim/lua/lsp/cmp.lua:55: attempt to index field 'preset' (a nil value)

### ISSUE THREAD

**Issue by fgqile** [nshen/learn-neovim-lua#35]
当打开nvim的时候，出现了这样的错误，作者有什么建议吗？

`
Error detected while processing /home/lzg/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/lzg/.config/nvim/lua/lsp/cmp.lua:55: attempt to index field 'preset' (a nil value)
stack traceback:
        /home/lzg/.config/nvim/lua/lsp/cmp.lua:55: in main chunk
        [C]: in function 'require'
        /home/lzg/.config/nvim/init.lua:27: in main chunk
Vimspector unavailable: Requires Vim compiled with +python3
Press ENTER or type command to continue
`

![image](https://user-images.githubusercontent.com/64899378/170965429-e4af26e7-4c3a-4522-bc28-de61fa9eca6f.png)

**Comment by nshen** [comment]
`init.lua:27: in main chunk Vimspector unavailable: Requires Vim compiled with +python3`

应该跟你neovim安装方式有关，需要+python3，或者你可以先把init.lua 27行注释掉试试

**Comment by fgqile** [comment]
我是ubunut18，下载的是neovim压缩包，解压后，添加环境变量，用这种方式安装的。怎么添加python3呀，我系统里面有python，也一直在用python

**Comment by fgqile** [comment]
已经解决了，我清除了所有插件，然后重新安装，之后没有问题了。
