### ISSUE TITLE
init.lua 报错 nvim-lsp-ts-utils 找不到

### ISSUE THREAD

**Issue by Linya-IronMan** [nshen/learn-neovim-lua#36]
![image](https://user-images.githubusercontent.com/77786952/171983597-ea549045-6ba7-4d9a-8873-fbbe65f89a50.png)

**Comment by Linya-IronMan** [comment]
直接 clone的作者的配置..

**Comment by nshen** [comment]
那是一个插件，网络问题没下载

**Comment by Linya-IronMan** [comment]
> 那是一个插件，网络问题没下载成功，卸载重下

确实是网络问题导致的插件安装失败，之前即使按照小册所说设置了全局代理也无法全部安装成功，之后设置了镜像站点才全部安装成功
