### ISSUE TITLE
Mac InserLeave 参数无效

### ISSUE THREAD

**Issue by Linya-IronMan** [nshen/learn-neovim-lua#37]
![image](https://user-images.githubusercontent.com/77786952/171994681-9ebcfb58-4a3a-4b6c-a05f-9b59a42db6b1.png)

![image](https://user-images.githubusercontent.com/77786952/171994686-07b497ec-dc72-4e1b-9cb3-85d3095fd874.png)

使用的是 Mac 电脑，在选择项目的时候出现，不知道是哪里的问题
![image](https://user-images.githubusercontent.com/77786952/171994732-2a09ba69-8ab8-4d1a-bc0d-a2b0709fac80.png)

**Comment by Linya-IronMan** [comment]
在小册上找到了原因，应该是 Mac 需要手动安装一下 im-select

**Comment by nshen** [comment]
对，这个是保证切换到normal模式时候会自动切换回英文输入法。 如果不需要可以注释掉那两段自动命令，或者安装im-select即可

`brew tap daipeihust/tap && brew install im-select`
