### ISSUE TITLE
语法高亮不生效

### ISSUE THREAD

**Issue by Linya-IronMan** [nshen/learn-neovim-lua#39]
nvim-treesitter 已经设置 tsinstall  已经安装 lua html 等语言
原始配置直接 clone，colorscheme 配置的是小册推荐的
checkhealth nvim-tresitter  信息如截图，没有一点思路
![image](https://user-images.githubusercontent.com/77786952/172039268-b69eade4-42b5-42cf-bd91-e845d7dc1484.png)

**Comment by nshen** [comment]
打开一个lua文件，运行看看 `:TSToggle highlight` 有效果吗

**Comment by Linya-IronMan** [comment]
> 

这个有试过，毫无效果

**Comment by Linya-IronMan** [comment]
> 打开一个lua文件，运行看看 `:TSToggle highlight` 有效果吗
这个有试过，毫无效果，就是使用的 lua 文件进行的测试

**Comment by nshen** [comment]
你这全绿色好怪啊，我不知道了，可能是系统，终端，或者neovim版本问题？

**Comment by Linya-IronMan** [comment]
> 你这全绿色好怪啊，我不知道了，可能是系统，终端，或者neovim版本问题？

好吧.... 实在不行我就照着小册一步一步重新来一遍

**Comment by nshen** [comment]
你这是什么系统，什么终端呀？

**Comment by Linya-IronMan** [comment]
> 

Mac M1 zsh应该

**Comment by nshen** [comment]
我的Mac M1 在 Iterm2 和 Alacritty 下都没问题

**Comment by Linya-IronMan** [comment]
> 

代码完全来自这个仓库么？

**Comment by Linya-IronMan** [comment]
> 嗯，应该是你用的终端不支持高亮，装个 iterm2吧。

芜湖 ... .真的是这个问题 .... 一换上item2 高亮就立马出来了...
