### ISSUE TITLE
配置 Lua 快捷键绑定问题

### ISSUE THREAD

**Issue by terrypang** [nshen/learn-neovim-lua#5]
您好。进行到 LSP 基础配置的部分，修改 lua/lsp/setup.lua，添加快捷键绑定的程序块，会出现：

attempt to index local 'opts' (a boolean value) 的提示。可能是哪里的问题？

谢谢！

**Comment by nshen** [comment]
hi @terrypang ， 把空语言配置文件，改成 `return {}`  就好了

**Comment by terrypang** [comment]
我配的是clangd，文件是clangd.lua。按照[文档](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd)，文件内容填写的是`require'lspconfig'.clangd.setup{}`。

现在我改成了`return {}`，测试了，能用了。谢谢。

**Comment by nshen** [comment]
> 我配的是clangd，文件是clangd.lua。按照[文档](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd)，文件内容填写的是`require'lspconfig'.clangd.setup{}`。
> 
> 现在我改成了`return {}`，测试了，能用了。谢谢。

对的，因为我统一调用了setup，所以clangd.lua只要return setup里边的参数就行了
