### ISSUE TITLE
windows terminal 中运行 Vim/ NeoVim 上下左右的黑边你不觉得很丑吗？

### ISSUE THREAD

**Issue by sober-wang** [nshen/learn-neovim-lua#7]
如题

**Comment by nshen** [comment]
hi @sober-wang 我也听别人说过有黑边，我自己都没察觉，没觉得哪里丑啊，你们指的黑边是这个吗

![image](https://user-images.githubusercontent.com/181506/149261401-0f38c24d-4625-4db7-a383-c5e0e85c0781.png)

**Comment by sober-wang** [comment]
对，但是我找到了解决办法。
![image](https://user-images.githubusercontent.com/35804630/149723068-900fd07e-2949-4a02-9bf2-90f9834e0c12.png)
