### ISSUE TITLE
根据你的知乎文档设置 lsp 的时候遇见的问题

### ISSUE THREAD

**Issue by sober-wang** [nshen/learn-neovim-lua#8]
![image](https://user-images.githubusercontent.com/35804630/149723206-03a41dbd-d99d-4f8d-a975-69d45ec5c8c4.png)
应该怎么解决呢？

以下是我的配置

![image](https://user-images.githubusercontent.com/35804630/149723940-8bf70ede-d656-4ce4-9562-f368c15b4ea5.png)

**Comment by nshen** [comment]
hi @sober-wang 看一下 `lua/lsp/lua.lua` 文件是不是空的，如果文件是空的，改成 `return {}`

这里列出的文件都得 `return {}`
![image](https://user-images.githubusercontent.com/181506/149745823-e14c8f45-b142-406f-9658-8ca9dd822e7b.png)

跟这些应该是一样的问题。

https://github.com/nshen/learn-neovim-lua/issues/2
https://github.com/nshen/learn-neovim-lua/issues/5

**Comment by sober-wang** [comment]
好的，谢谢啦。暂时先这样吧，lua 模式还是太新了，我使用 Golang ，他们这块配置好像还有问题。我已经切回 Coc 了，谢谢博主。

**Comment by nshen** [comment]
@sober-wang  我是不会golang，这个大佬配置的go好像很厉害，https://github.com/ray-x/go.nvim

**Comment by sober-wang** [comment]
谢啦！
