### ISSUE TITLE
催更催更催更催更催更~~~~~~！

### ISSUE THREAD

**Issue by BreakingLead** [nshen/learn-neovim-lua#9]

**Comment by nshen** [comment]
谢大佬支持，不好的消息，这个版本可能暂时不会更了，签合约写掘金小册了，按要求重新写了，写得更详细了，到时候愿意支持收费版本的话，预售时有折扣。不愿意支持的话可以直接参考dev分支的代码

**Comment by BreakingLead** [comment]
质量很高，出了一定支持！
